README.md

doc: add badge

---

.github/workflows/build.yml
package.json
yarn.lock

chore: upgrade projen and deps #86

---

.github/workflows/upgrade-dependencies.yml
.projenrc.js

chore: update deps workflow

---

.github/workflows/release.yml
.projen/tasks.json
.projenrc.js
package.json

fix: publish to pypi typo

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade-projen.yml
.projen/deps.json
package.json
yarn.lock

chore: upgrade-projen

---

package.json
yarn.lock

chore: upgrade jest to v27

---

lambda/Makefile
lambda/go.mod
lambda/go.sum

refers to https://github.com/containers/skopeo/commit/5c82c7728f621c3b48faf299d26772daf38c3b2a
Fixes #140

fix: security issue

---

README.md
lambda/.dockerignore
lambda/Dockerfile
lambda/Makefile
lambda/go.sum
src/index.ts
test/integ.ecr-deployment.ts

chore: refactor: build lambda

---

.github/workflows/release.yml
.projenrc.js

fix: release lambda error

---

.projen/deps.json
.projenrc.js
package.json
yarn.lock

chore: upgrade projen to v0.38.0

---

src/index.ts

fix: package subpath './core' is not defined by exports

---

lambda/go.mod
lambda/go.sum

chore: go mod tidy

---

.github/workflows/release-v1-main.yml
.github/workflows/release.yml
.projenrc.js

fix: release_prebuilt_lambda error

---

.github/workflows/upgrade-main.yml
.github/workflows/upgrade-v1-main.yml
.projen/tasks.json
.projenrc.js
package.json

chore: remove AUTOMATION env

---

lambda/Dockerfile

Fixes # Docker hub rate limiting

feat: Pull from ECR repo

---

.projen/deps.json
.projen/tasks.json
.projenrc.js
API.md
lambda/Dockerfile
lambda/install.js
package.json
src/index.ts
test/integ.ecr-deployment.ts
yarn.lock

Make download to work from behind the proxy
Fixes #170

feat: Allow definition of used base image for lambda build

---

README.md

fix: external repo docs

---

README.md

fix: documentation related to secret usage

---

lambda/Dockerfile

chore: change GOPROXY separator to pipe(|) #183

---

package.json
yarn.lock

Reverts cdklabs/cdk-ecr-deployment#167

fix: Revert "chore(deps): upgrade dependencies"

---

lambda/Dockerfile
test/lambda/Dockerfile

chore: try remove go mod download to see if we can speed up build time

---

README.md

chore: update README to inform users that 1.* is no longer supported

---

lambda/install.js

Fixes https://github.com/cdklabs/cdk-ecr-deployment/issues/292

fix: use proxy to download main.sha256

---

src/index.ts

fix: use golang image from public.ecr.aws

---

.github/workflows/build-lambda.yml

chore: specify a node version for GHA

---

API.md
README.md
src/index.ts
test/dockerhub-example.ecr-deployment.ts
test/example.ecr-deployment.ts
test/lambda/test.sh

Fixes #419
Also makes the test script more flexible for non standard environments

chore: make examples deployable and improve documentation for running examples

---

.projen/deps.json
.projen/tasks.json
.projenrc.ts
package.json
yarn.lock

Also upgrades some MV of other dev dependencies

fix: upgrade to jsii and typescript 5.7
